// Store the actions in a separate file to avoid Webpack issues when importing them in the Studio
// source code

export enum SiteCommandLoggerAction {
	START_DAEMON = 'startDaemon',
	LOAD_SITES = 'loadSites',
	START_PROXY = 'startProxy',
	STOP_PROXY = 'stopProxy',
	GENERATE_CERT = 'generateCert',
	DELETE_CERT = 'deleteCert',
	ADD_DOMAIN_TO_HOSTS = 'addDomainToHosts',
	REMOVE_DOMAIN_FROM_HOSTS = 'removeDomainFromHosts',
	START_SITE = 'startSite',
	STOP_SITE = 'stopSite',
	STOP_ALL_SITES = 'stopAllSites',
	SET_WP_VERSION = 'setWpVersion',
	VALIDATE = 'validate',
	CREATE_DIRECTORY = 'createDirectory',
	INSTALL_SQLITE = 'installSqlite',
	ASSIGN_PORT = 'assignPort',
	SETUP_WORDPRESS = 'setupWordPress',
	SAVE_SITE = 'saveSite',
	APPLY_BLUEPRINT = 'applyBlueprint',
	EXTRACT_BACKUP = 'extractBackup',
	IMPORT_SITE = 'importSite',
	IMPORT_DATABASE = 'importDatabase',
	IMPORT_WP_CONTENT = 'importWpContent',
	IMPORT_META = 'importMeta',
	EXPORT_SITE = 'exportSite',
	CREATE_BACKUP = 'createBackup',
	EXPORT_DATABASE = 'exportDatabase',
	EXPORT_WP_CONTENT = 'exportWpContent',
	EXPORT_CONFIG = 'exportConfig',
	DELETE_FILES = 'deleteFiles',
	ENSURE_PHP_BINARY = 'ensurePhpBinary',
}

export enum DeployCommandLoggerAction {
	LOAD_SITES = 'loadSites',
	INSTALL_SQLITE = 'installSqlite',
	CONNECT = 'connect',
	PREFLIGHT = 'preflight',
	EXPORT_DATABASE = 'exportDatabase',
	REWRITE_URLS = 'rewriteUrls',
	SYNC_FILES = 'syncFiles',
	UPLOAD_DATABASE = 'uploadDatabase',
	IMPORT_DATABASE = 'importDatabase',
}
